#!/bin/bash
domain=$(cat /etc/xray/domain)
uuid=$(uuid)
#MASUKAN
run_masukan() {
read -p "Username         : " user
read -p "Quota (GB)       : " quota
read -p "Max Ip login     : " iplimit
read -p "Masaaktif        : " masaaktif
}

#QUOTA
run_quota() {
if [[ $quota -gt 0 ]]; then
echo -e "$[$quota * 1024 * 1024 * 1024]" > /etc/funny/limit/vless/quota/$user
else
echo > /dev/null
fi
}

#IPLIMIT
run_iplimit() {
if [[ $iplimit -gt 0 ]]; then
echo -e "$iplimit" > /etc/funny/limit/vless/ip/$user
else
echo > /dev/null
fi
}

#CEK_USER        
run_cek_user() {        
akun=$(cat /etc/xray/vless-grpc.json | grep $user -o | uniq | wc -l)
if [ $akun = 0 ]; then
clear
echo > /dev/null
else
clear
echo -e "user telah digunakan"
echo -e "silahkan gunakan nama user lain"
exit
fi
}

#WRITE_JSON
run_write_json() {            
now=`date -d "0 days" +"%Y-%m-%d"`
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#xray$/a\#### '"$user$sec $exp"'\
},{"id": "'""$uuid""'","email": "'""$user$sec""'"' /etc/xray/vless*
ws="vless://${uuid}@${domain}:443?path=%2Fvlessws&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}"
grpc="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
none="vless://${uuid}@${domain}:80?path=%2Fvlessws&security=none&encryption=none&host=${domain}&type=ws#${user}"
sleep 15 && systemctl restart vless-ws &
sleep 15 && systemctl restart vless-grpc &
clear
}
            
#OUTPUT_AKUN
run_output_akun() {                 
echo -e "══════════════════════════"                 
echo -e "    <=  VLESS ACCOUNT =>"       
echo -e "══════════════════════════"                 
echo -e ""                
echo -e "Username     : $user"
echo -e "CITY         : $(cat /root/.mycity)"
echo -e "ISP          : $(cat /root/.myisp)"
echo -e "Host/IP      : $domain"
echo -e "Port         : 443, 80"
echo -e "Key          : $uuid"
echo -e "Network      : ws, grpc"
echo -e "Path TLS     : /vlessws"
echo -e "serviceName  : vless-grpc"               
echo -e ""  
echo -e "══════════════════════════"                 
echo -e "Link Tls  => ${ws}"
echo -e "══════════════════════════"                 
echo -e "Link None => ${none}"
echo -e "══════════════════════════"                 
echo -e "Link Grpc => ${grpc}"
echo -e "══════════════════════════"                 
echo -e "     Expired => $exp"
echo -e "══════════════════════════"                 
}
            
run_tele() {
telegram-send --pre "$(run_output_akun)"                        
}               

#execute    
run_masukan
run_quota
run_iplimit
run_cek_user
run_write_json   
run_output_akun    
run_tele > /dev/null &            
            
